name: Analyze and test the code

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string
        description: 'The module to process.'
      os-version:
        required: true
        type: string
        description: ''
      python-version:
        required: true
        type: string
        description: ''
      weewx-version:
        required: true
        type: string
        description: ''
      latest-os-version:
        required: true
        type: string
        description: ''
      latest-python-version:
        required: true
        type: string
        description: ''
      latest-weewx-version:
        required: true
        type: string
        description: ''
      pip-list:
        required: true
        type: string
        description: 'Additional pip packages to be installed.'
      package-list:
        required: true
        type: string
        description: 'Additional OS packages to be installed.'
      artifact-name-suffix:
        required: true
        type: string
        description: ''
      lint:
        required: true
        type: boolean
      unit-test:
        required: true
        type: boolean
      function-test:
        required: true
        type: boolean
      integration-test:
        required: true
        type: boolean
      e2e-test:
        required: true
        type: boolean
      code-coverage:
        required: true
        type: boolean
      coveralls-upload:
        required: true
        type: boolean
      codecov-upload:
        required: true
        type: boolean
      sonar-scan:
        required: true
        type: boolean
    secrets:
      CODECOV_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  build:
    name: ${{ inputs.os-version}} ${{ inputs.python-version }} ${{ inputs.weewx-version }}
    runs-on: ${{ inputs.os-version}}

    steps:
    - uses: actions/checkout@v5
    - name: Log inputs
      run: |
        echo "INPUT: env.ACT: ${{env.ACT}}"
        echo "INPUT: module-name:           ${{inputs.module-name}}"
        echo "INPUT: os-version:            ${{inputs.os-version}}"
        echo "INPUT: python-version:        ${{inputs.python-version}}"
        echo "INPUT: weewx-version:         ${{inputs.weewx-version}}"
        echo "INPUT: latest-os-version:     ${{inputs.latest-os-version}}"
        echo "INPUT: latest-python-version: ${{inputs.latest-python-version}}"
        echo "INPUT: latest-weewx-version:  ${{inputs.latest-weewx-version}}"
        echo "INPUT: pip-list:              ${{inputs.pip-list}}"
        echo "INPUT: package-list:          ${{inputs.package-list}}"
        echo "INPUT: artifact-name-suffix:  ${{inputs.artifact-name-suffix}}"
        echo "INPUT: lint:                  ${{inputs.lint}}"
        echo "INPUT: unit-test:             ${{inputs.unit-test}}"
        echo "INPUT: function-test:         ${{inputs.function-test}}"
        echo "INPUT: integration-test:      ${{inputs.integration-test}}"
        echo "INPUT: e2e-test:              ${{inputs.e2e-test}}"
        echo "INPUT: code-coverage:         ${{inputs.code-coverage}}"
        echo "INPUT: coveralls-upload:      ${{inputs.coveralls-upload}}"
        echo "INPUT: codecov-upload:        ${{inputs.codecov-upload}}"
        echo "INPUT: sonar-scan:            ${{inputs.sonar-scan}}"

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        source .venv/bin/activate

        python -m pip install --upgrade pip
        python -m pip install coverage coveralls configobj mock pylint pytest pytest-cov pytest-html

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        if [ "${{inputs.pip-list}}" != "" ]; then 
          python -m pip install ${{inputs.pip-list}}; 
        fi

        sudo apt-get update

        if [ "${{inputs.package-list}}" != "" ]; then sudo apt-get -qq --assume-yes install ${{inputs.package-list}}; fi

    - name: Install WeeWX (${{ inputs.weewx-version }})
      run: |
        source .venv/bin/activate

        WEEWX_VERSION=${{inputs.weewx-version}}
        if [ ${WEEWX_VERSION:0:6} == 'branch' ]; then
          pip install git+https://github.com/weewx/weewx.git@${WEEWX_VERSION:7}
        else
          python -m pip install weewx==${{ inputs.weewx-version }}
        fi
  
    - name: Lint with pylint
      if: ${{inputs.lint}}
      run: |
        source .venv/bin/activate

        mkdir -p results
        pylint ./bin/user/${{inputs.module-name}}.py -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" | tee results/pylint.txt
    
    - name: Unit tests
      if: ${{inputs.unit-test}}
      run: |
        source .venv/bin/activate

        export PYTHONPATH=bin:$PYTHONPATH
        pytest bin/user/tests/unit --html=results/unittests.html --self-contained-html
    
    - name: Function tests
      if: ${{inputs.function-test}}
      run: |
        source .venv/bin/activate

        export PYTHONPATH=bin:$PYTHONPATH
        pytest bin/user/tests/func --html=results/functests.html --self-contained-html

    - name: Integration tests
      if: ${{inputs.integration-test}}
      run: |
        source .venv/bin/activate

        export PYTHONPATH=bin:$PYTHONPATH
        pytest bin/user/tests/integ --html=results/integtests.html --self-contained-html

    - name: E2E tests
      if: ${{inputs.e2e-test}}
      run: |
        source .venv/bin/activate

        export PYTHONPATH=bin:$PYTHONPATH
        pytest bin/user/tests/e2e --html=results/e2etests.html --self-contained-html

    - name: Code Coverage
    # Only run code coverage once, against the latest python version and weewx version
      if: ${{ inputs.os-version == inputs.latest-os-version &&
              inputs.python-version == inputs.latest-python-version && 
              inputs.weewx-version == inputs.latest-weewx-version}}
      run: |
        source .venv/bin/activate

        export PYTHONPATH=bin:$PYTHONPATH
        coverage run --branch -m pytest bin/user/tests/unit
        # Create a human readable coverage report
        coverage html --include bin/user/${{inputs.module-name}}.py -d results/coverage
        # Create an xml coverage report, used by: coveralls, codecov, sonar
        coverage xml --include bin/user/${{inputs.module-name}}.py
  
    - name: Archive test-results
      uses: actions/upload-artifact@v5
      with:
        name: test-${{ inputs.os-version }}-${{ inputs.python-version }}-${{ inputs.weewx-version }}${{inputs.artifact-name-suffix}}
        path: results

    - name: Upload coverage to Coveralls 
    # Do not attempt to upload on local runs, could not get it to work
      if: ${{ !env.ACT && inputs.coveralls-upload &&
              inputs.os-version == inputs.latest-os-version &&
              inputs.python-version == inputs.latest-python-version && 
              inputs.weewx-version == inputs.latest-weewx-version}}
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
        file: coverage.xml

    - name: Upload coverage to Codecov
      if: ${{ !env.ACT && inputs.codecov-upload &&
              inputs.os-version == inputs.latest-os-version &&
              inputs.python-version == inputs.latest-python-version && 
              inputs.weewx-version == inputs.latest-weewx-version}}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        override_branch: ${{ env.ACT && 'local' || '' }}
        override_commit: ${{ env.ACT && 'local' || '' }}

    - name: SonarQube Scan
      # Do not attempt to upload on local runs, sonar (free) does not support branch analysis
      if: ${{ !env.ACT && inputs.sonar-scan && 
              inputs.os-version == inputs.latest-os-version &&
              inputs.python-version == inputs.latest-python-version && 
              inputs.weewx-version == inputs.latest-weewx-version}}
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
