name: TEST perform analyze and test

on:
  push:

jobs:
  analyze-test:
    uses: ./.github/workflows/perform-analyze-test.yml
    with:
      module-name: 'simpleclass'
      os-version: 'ubuntu-24.04'
      # Versions higher than 3.11 require a virtual environment to run
      python-version: '3.11'
      weewx-version: '5.2.0'
      latest-os-version: 'ubuntu-24.04'
      latest-python-version: '3.11'
      latest-weewx-version: '5.2.0'
      pip-list: ''
      package-list: ''
      artifact-name-suffix: ''
      flake-extra-parms: ''
      lint: true
      unit-test: true
      function-test: true
      integration-test: true
      code-coverage: true
      coveralls-upload: true
      codecov-upload: true
      sonar-scan: true
    secrets:
      #COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}