name: TEST the full analyze and test workflow

on:
  push:
    branches: [ "master" ]
    #branches-ignore: [ "master" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: ./.github/workflows/full-analyze-test.yml
    with:
      module-name: 'simpleclass'
      #pip-list: 'paho-mqtt'
      #package-list: 'mosquitto'
      coveralls-upload: true
      codecov-upload: true
      sonar-scan: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}